"""add delete with parent

Revision ID: aa4897dd59de
Revises: f66e582b891a
Create Date: 2026-06-17 17:19:11.358390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa4897dd59de'
down_revision: Union[str, Sequence[str], None] = 'f66e582b891a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('delete_with_parent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'delete_with_parent')
    # ### end Alembic commands ###
