"""add updated_at and deleted_at

Revision ID: f66e582b891a
Revises: af502969ba65
Create Date: 2026-06-16 19:22:27.423822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66e582b891a'
down_revision: Union[str, Sequence[str], None] = 'af502969ba65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('notes', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('notes', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('notes', 'deleted_at')
    op.drop_column('notes', 'updated_at')
    op.drop_column('job_applications', 'deleted_at')
    # ### end Alembic commands ###
